PREFIX : <http://www.6starhome.com/company/> 
PREFIX  owl: <http://www.w3.org/2002/07/owl#> 
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#> 
 
SELECT ?x ?name
{
	?x  :Name <mailto:alice@example> .
	?x  rdf:type ?a1 .
	?a1 foaf:knows ?a2 .    
	?a2 foaf:name ?name .   
	?y :Name ?z .
}
